Disable search in integration tests subfolders
because the current version of the codecov uploader crash if a broken link is found:

Traceback (most recent call last):
  File "codecov_cli/main.py", line 83, in <module>
  File "codecov_cli/main.py", line 79, in run
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1688, in invoke
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "click/decorators.py", line 33, in new_func
  File "codecov_cli/commands/upload.py", line 257, in do_upload
  File "codecov_cli/services/upload/__init__.py", line 78, in do_upload_logic
  File "codecov_cli/services/upload/upload_collector.py", line 174, in generate_upload_data
  File "codecov_cli/services/upload/upload_collector.py", line 100, in _produce_file_fixes
  File "codecov_cli/services/upload/upload_collector.py", line [114](https://github.com/arduino/arduino-cli/actions/runs/9112950400/job/25053833785?pr=2522#step:8:115), in _get_file_fixes
FileNotFoundError: [Errno 2] No such file or directory: 'internal/integrationtest/compile_4/testdata/ValidSketchWithNonInoBrokenSketchFileSymlink/other_file.c'